<?php

namespace rocketfellows\MSTeamsWebhookMessageSender\exceptions\configs;

use rocketfellows\MSTeamsWebhookMessageSender\exceptions\MSTeamsWebhookMessageSenderException;

abstract class MSTeamsWebhookConnectorException extends MSTeamsWebhookMessageSenderException
{
}
