<?php

namespace rocketfellows\MSTeamsWebhookMessageSender\exceptions\message;

use rocketfellows\MSTeamsWebhookMessageSender\exceptions\MSTeamsWebhookMessageSenderException;

abstract class MSTeamsWebhookMessageException extends MSTeamsWebhookMessageSenderException
{
}
