<?php

namespace rocketfellows\MSTeamsWebhookMessageSender\exceptions\request;

use rocketfellows\MSTeamsWebhookMessageSender\exceptions\MSTeamsWebhookMessageSenderException;

abstract class MSTeamsWebhookSenderException extends MSTeamsWebhookMessageSenderException
{
}
